export const SET_CURRENT_PAGE= "SET_CURRENT_PAGE";
export const GET_BY_NAME='GET_BY_NAME';
export const ALL_POKEMON= 'ALL_POKEMON'
export const ALL_TYPES= 'ALL_TYPES'
export const POKEMON_NAME= 'POKEMON_NAME'
export const ORDER_NAME= 'ORDER_NAME'
export const ORDER_ATTACK= 'ORDER_ATTACK'
export const ORDER_TYPES= 'ORDER_TYPES'
export const ORDER_ORIGIN= 'ORDER_ORIGIN'
export const FAILURE='FAILURE'